config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"


  root 'posts#index'

  devise_for :users
  # get 'profile', to: 'users#show', as: 'profile'

  resources :users, only: [:show] do
    collection do
      get :search  # Search for users by username
    end
  end

  resources :posts do
    resources :comments
  end

  resources :follows, only: [:create, :destroy] do
    collection do
      get :followers  # List followers
      get :following  # List following users
      get :pending_requests  # List pending follow requests
    end

    member do
      patch :accept  # Accept a follow request
    end
  end

  resources :chats, only: [:create, :update, :destroy]
  get 'conversation/:user_id', to: 'chats#conversation', as: :conversation
  get 'recent_chats', to: 'chats#recent_chats', as: :recent_chats

  resources :notifications, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  validates :content, presence: true
  # validates :location, presence: true
  validate :validate_image_type

  after_create :analyze_sentiment

  private

  def analyze_sentiment
    self.sentiment_score = 0.5
    self.sentiment_type = "positive"
    save
  end

  def validate_image_type
    images.each do |image|
      if !image.content_type.in?(%w[image/jpeg image/png image/gif])
        errors.add(:images, "must be a JPEG, PNG, or GIF")
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:location].present?
      @posts = Post.where(location: params[:location])
    else
      @posts = Post.all
    end
    # @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @comment = @post.comments.new
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if post_params[:latitude] && post_params[:longitude]
      # @post.location = GoogleMapsService.get_location(params[:latitude], params[:longitude])
      @post.location = Geocoder.search([post_params[:latitude], post_params[:longitude]]).first.address
    elsif request.location
      @post.location = request.location.address
    end

    if @post.save
      redirect_to posts_url, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post
  end

  def update
    if @post.update(post_params)
      redirect_to posts_url, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :latitude, :longitude, :location, images: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post) do |form| %>
  <% if @post.errors.any? %>
    <div>
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :images, "Attach Images" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', post_path(@post) %>

app/views/posts/index.html.erb
<h1 class="header">
  Instalink
  <%= link_to recent_chats_path, style: 'float: right; margin-left: 10px;' do %>
    <%= image_tag 'chat.png', alt: 'Chat', size: "30x30", style: 'vertical-align: middle;' %>
  <% end %>
  <%= link_to notifications_path, style: 'float: right; margin-left: 10px;' do %>
    <%= image_tag 'notification.png', alt: 'Notifications', size: "30x30", style: 'vertical-align: middle;' %>
  <% end %>
</h1>

<% @posts.each do |post| %>
  <div class="post-card">
    <div style="display: flex; align-items: center; justify-content: space-between; padding: 10px;">
      <div style="display: flex; align-items: center;">
        <% if post.user.profile_picture.attached? %>
          <%= image_tag post.user.profile_picture, size: "40x40", style: "border-radius: 50%; margin-right: 10px;" %>
        <% else %>
          <%= image_tag "profile_picture_default.jpeg", size: "40x40", style: "border-radius: 50%; margin-right: 10px;" %>
        <% end %>
        <div>
          <h4 style="margin: 0; font-size: 24px;">
            <%= link_to post.user.username, user_path(post.user), style: "text-decoration: none; color: inherit;" %>
          </h4>
          <% if post.location.present? %>
            <p style="margin: 0; font-size: 12px; color: gray;">
              <%= link_to post.location, posts_path(location: post.location), style: "text-decoration: none; color: inherit;" %>
            </p>
          <% end %>
        </div>
      </div>
      <% if post.user == current_user %>
        <div style="display: flex; gap: -5px; align-items: center;">
          <%= link_to 'Edit', edit_post_path(post), style: "text-decoration: none; font-size: 16px; color: blue;" %>
          <%= button_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, style: "font-size: 16px; color: red; background: none; border: none; text-decoration: none; cursor: pointer;" %>
        </div>
      <% end %>
    </div>

    <% if post.images.attached? %>
      <div style="display: flex; flex-wrap: wrap; justify-content: center; align-items: center;">
        <% post.images.each do |image| %>
          <%= image_tag image, size: "300x300", style: "margin: 10px;" %>
        <% end %>
      </div>
    <% else %>
      <p style="text-align: center; font-size: 18px; color: gray;">No images attached.</p>
    <% end %>
    <div style="padding: 10px;">
      <div class="comments-section">
        <%= link_to image_tag('comment.png', size: "16x16", alt: "Comments", class: "comment-icon"), post_path(post) %>
      </div>
      <div style="font-size: 12px; color: gray; margin-bottom: 5px;">
        <p style="margin: 0;">
          <b style="font-size: 12px; color: inherit;"><%= post.user.username %>:</b> 
          <span style="font-size: 12px; color: inherit;"><%= post.content %></span>
        </p>
      </div>
      <p style="font-size: 12px; color: gray; margin: 0;">
        <%= time_ago_in_words(post.created_at) %> ago
      </p>
    </div>
  </div>
<% end %>

<%= link_to 'New Post', new_post_path, class: 'new-post-button' %>

<% if current_user %>
  <div class="user-icon">
    <%= link_to image_tag('user_icon.png', alt: 'User Icon', class: 'icon'), user_path(current_user) %>
  </div>
<% end %>

<div class="search-section">
  <%= form_with url: search_users_path, method: :get, local: true, class: 'search-form' do %>
    <%= text_field_tag :query, params[:query], placeholder: "Search users...", class: 'search-input' %>
    <%= submit_tag "Search", class: 'search-button' %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post) do |form| %>
  <% if @post.errors.any? %>
    <div>
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :images, "Attach Images" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div id="location-container">
    <%= form.hidden_field :location, id: "post_location" %>
    <%= form.hidden_field :latitude, id: "post_latitude" %>
    <%= form.hidden_field :longitude, id: "post_longitude" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %>

<script>
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      console.log(position.coords.latitude);  // Log the latitude to console
      console.log(position.coords.longitude); // Log the longitude to console

      document.getElementById("post_latitude").value = position.coords.latitude;
      document.getElementById("post_longitude").value = position.coords.longitude;
    });
  } else {
    alert("Geolocation is not supported by this browser.");
  }
</script>

app/views/posts/show.html.erb
<h1><%= @post.user.username %></h1>
<p><%= @post.location %></p>

<% if @post.images.attached? %>
  <div style="text-align: center;">
    <% @post.images.each do |image| %>
      <%= image_tag image, size: "300x300", style: "display: inline-block; margin: 10px;" %>
    <% end %>
  </div>
<% else %>
  <p>No images attached.</p>
<% end %>

<h3><small><%= @post.content %></small></h3>

<h2>Comments</h2>

<% if @comments.any? %>
  <ul>
    <% @comments.each do |comment| %>
      <li>
        <span><strong><%= comment.user.username %></strong>:</span>
        <span><%= comment.content %></span>

        <% if comment.user == current_user %>
          <span>
            <%= form_with(model: [@post, comment], local: true, method: :patch) do |form| %>
              <%= form.text_area :content, rows: 1, style: "width: 300px; display: inline;" %>
              <%= form.submit "Update Comment", style: "display: inline;" %>
            <% end %>
          </span>
          <span>
            <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" }, style: "display: inline;" %>
          </span>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No comments yet. Be the first to comment!</p>
<% end %>

<h3>Leave a Comment</h3>
<%= form_with(model: [@post, @comment], local: true) do |form| %>
  <div>
    <%= form.label :content, "Your Comment:" %>
    <%= form.text_area :content, rows: 3 %>
  </div>
  <div>
    <%= form.submit "Post Comment" %>
  </div>
<% end %>